# Generated by Django 2.2.16 on 2020-09-21 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Register your username(Less than 20 letters)', max_length=20)),
                ('register_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the article up to 50 letters', max_length=50)),
                ('context', models.TextField(help_text='Enter your context here')),
                ('points', models.IntegerField()),
                ('upload_date', models.DateField(editable=False)),
                ('last_modified', models.DateField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.User')),
            ],
        ),
    ]
