# Generated by Django 2.2.16 on 2020-09-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200921_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='replies',
            field=models.CharField(default='Enter your reply here', max_length=100),
        ),
    ]
