# Generated by Django 2.2.16 on 2020-09-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_article_replies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('replies', models.CharField(default='Enter your reply here', max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='article',
            name='replies',
        ),
    ]
