# Generated by Django 2.2.16 on 2020-09-23 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200923_1922'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='replies',
            new_name='context',
        ),
        migrations.RemoveField(
            model_name='article',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='reply',
            name='upload_date',
        ),
    ]
