# Generated by Django 2.2.16 on 2020-09-28 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200923_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='article',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='reply', to='blog.Article'),
            preserve_default=False,
        ),
    ]
